
version: "3"
services:
  jellyweb-media:
   image: jellyfin/jellyfin
   container_name: jellyweb-media
   volumes:
    - ./jellyfin/config:/config
    - ./jellyfin/cache:/cache
    - ./data:/media/data
   networks: 
    - jwebNet
   restart: unless-stopped

  jellyweb-http:
   build:
    context: .
    dockerfile: Dockerfile
   container_name: jellyweb-http
   ports:
    - 80:80
    - 443:443
   networks:
    - jwebNet
   restart: unless-stopped
   hostname: media.jackcowling.local

networks:
  jwebNet:
    name: jwebNet
    external: 
      false

