#!bin/bash

DOMAIN=$1

if [ -d "conf/nginx" ]; then
	if test -f conf/nginx/nginx.conf; then
		rm conf/nginx/nginx.conf
	fi
else
	mkdir -p conf/nginx
fi
. scripts/inc-nginx-conf.sh >> conf/nginx/nginx.conf

if test -f Dockerfile; then
	rm Dockerfile
fi
. scripts/inc-dockerfile.sh >> Dockerfile

if test -f docker-compose.yml; then
	rm docker-compose.yml
fi
. scripts/inc-docker-compose.sh >> docker-compose.yml

docker compose up --build -d